### ISSUE TITLE
Please add english comments

### ISSUE THREAD

**Issue by infinitygamer404** [Minecraft-in-python/Minecraft#10]
I would really appreciate it if you guys added a english branch for this game and wrote the comments and README in english
I will gladly help if you need

**Comment by jason-bowen-zheng** [comment]
Add English version README is a easy thing.

I will add it to every repos.

**Comment by jason-bowen-zheng** [comment]
Create a project on <http://crowdin.com> isn't free, it needs **DOLLAR** monthly!
The organization haven't enough money, so we just translate it to Chinese, English and Spanish.

**Comment by infinitygamer404** [comment]
> Add English version README is a easy thing.
> 
> I will add it to every repos.

@jason-bowen-zheng thanks, that will help others



> Create a project on http://crowdin.com isn't free, it needs **DOLLAR** monthly!
> The organization haven't enough money, so we just translate it to Chinese, English and Spanish.

it's ok that the game only has those languages, it doesn't need more languages than those at the moment, but I think you misunderstood me. I said *add an english branch* with *english comments* and not more languages. By comments, I mean the comments in your code 
```# This is a comment```
currently all the comments in your code are in chinese, which I don't understand. I could use a translation software to translate it but the translation is not so good. So, adding an English branch with all the comments english would be nice.
Or maybe I could just translate it with Google translate and just go from there. :D

**Comment by jason-bowen-zheng** [comment]
**WTF??** 这个项目的大部分包含注释的代码从[这里](https://github.com/fogleman/Minecraft)复制过来, 且翻译了所有的注释. 你的意思是让我重新把我翻译完成的注释全部转换成英语中??

> Above is Chinese, so you must translate it

**Comment by ismaelxyz** [comment]
Hello @infinitygamer404, 
I will translate the "README", it is impossible to translate the comments from Chinese to English, but it is possible
to create new comments in English, I have seen your profile and to some extent I share your love for helping
Free Software projects.
One more thing, please note that your request was (is) already impossible. Imagine, what project has done
something like that?

I wonder, do you have any doubts regarding our project?

**Comment by jason-bowen-zheng** [comment]
@ismaelxyz Your translation about README wasn't very good!

**Comment by ismaelxyz** [comment]
I will fix my mistake and edit the others as well, I was a bit busy (other community issues). But can you tell me what I don't see (by some discreet means, of which we have)

**Comment by ismaelxyz** [comment]
It shows, my stress..., since you left me this responsibility, I'm like... tired,
how can you take so much pressure? :) Hahaha.

**Comment by TechDudie** [comment]
@jason-bowen-zheng, i live in the US, and i speak english, and a little bit of chinese, but Python dosent speak chinese it appears.
Python crashes due to the chinese comments it seems.

**Comment by jason-bowen-zheng** [comment]
> @jason-bowen-zheng, i live in the US, and i speak english, and a little bit of chinese, but Python dosent speak chinese it appears.
> Python crashes due to the chinese comments it seems.
> Therefore i suggest adding the "bug" label too.

A good suggestion! But I think Chinese comments and English comments should both exist.

**Comment by ismaelxyz** [comment]
"Python crashes due to the chinese comments it seems.".
That makes no sense, there is only one scenario (two but I don't think you use python2) where something like that can happen, but still, if you have something to report I am listening.

**Comment by jason-bowen-zheng** [comment]
> "Python crashes due to the chinese comments it seems.".
> That makes no sense, there is only one scenario (two but I don't think you use python2) where something like that can happen, but still, if you have something to report I am listening.

I'm very curious about that scenario

**Comment by TechDudie** [comment]
Yeah, I’m using python3

**Comment by jason-bowen-zheng** [comment]
> Yeah, I’m using python3

@TechDudie It's a wise decision. Minecraft-in-python can only run on python3
