### ISSUE TITLE
关于暂时迁移管理员权限

### ISSUE THREAD

**Issue by jason-bowen-zheng** [Minecraft-in-python/Minecraft#12]
Minecraft-in-python 的所有者 @jason-bowen-zheng 以及成员 @wzh656 将不再对该组织有规律得提交, 直至2021年6月底. 这段时间, 管理员为 @ismaelxyz , 他可以做任何事情, 但是不允许删除现有的仓库, 也没有必要新建仓库.

@jason-bowen-zheng 建议应该在服务器方面进行更多的提交.

祝好!
<p align="right"> @jason-bowen-zheng 于2021年2月21日</p>

**Comment by wzh656** [comment]
唉，终于要准备备战中考了，倒计时114天

**Comment by jason-bowen-zheng** [comment]
这个 issue 被锁定因为这只是一则公告.
