### ISSUE TITLE
Game settings

### ISSUE THREAD

**Issue by dmarakom6** [Minecraft-in-python/Minecraft#24]
I would like to have a game settings menu, where I can change the sensitivity or the brightness.

**Comment by jason-bowen-zheng** [comment]
A good idea! I'll try it.

Maybe we need help.

**Comment by dmarakom6** [comment]
I'd love to help!

**Comment by jason-bowen-zheng** [comment]
Would you give me some advice?

**Comment by dmarakom6** [comment]
Sure!

# Visual Implementation
Just like the rest of the rest of the game menu, add a button labeled "Game Settings" along with the "Back To Game" & "Exit" buttons. This button redirects the user to a sub-menu, where he can find brightness or sensitivity sliders (if sliders sound like a huge leap, you can use simple input fields).

# Functional Implementation
Depending on the user's input, change `utils.brightness`, or the variables that are responsible for the player's sensitivity.

I recently forked the project, so I can try working on these features if you're too busy.

**Comment by jason-bowen-zheng** [comment]
Use tk to implement? No, to copy the real Minecraft, I would use pyglet to rewrite the game settings menu(or start screen). I'll implement the slider soon.

**Comment by dmarakom6** [comment]
Tkinter sounds like a good solution.

**Comment by jason-bowen-zheng** [comment]
> Tkinter sounds like a good solution.

Did you play Minecraft? The Game Settings Screen and Game Screen are in one Window.

Maybe it's a good solution, in launcher.

**Comment by dmarakom6** [comment]
I did try it, and I loved it.
So, the menu can be an extra button in the same window. Alternatively, it could be a new tk() window from the launcher.
