### ISSUE TITLE
Unable to un on macOS

### ISSUE THREAD

**Issue by jianhaoye2** [Minecraft-in-python/Minecraft#28]
> When I run below code

> python3 -m minecraft

2021-10-19 22:13:16.566 python[25991:10100648] -[NSApplication macMinorVersion]: unrecognized selector sent to instance 0x7fe7f0672090
2021-10-19 22:13:16.571 python[25991:10100648] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSApplication macMinorVersion]: unrecognized selector sent to instance 0x7fe7f0672090'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007fff345a8be7 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff6d1e75bf objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff34627c77 -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007fff3450d44b ___forwarding___ + 1427
	4   CoreFoundation                      0x00007fff3450ce28 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x000000010f0f2db9 SetCGColorComponents + 265
	6   libtk8.6.dylib                      0x000000010f0f367a TkpGetColor + 250
	7   libtk8.6.dylib                      0x000000010f02daa9 Tk_GetColor + 153
	8   libtk8.6.dylib                      0x000000010f01d8e6 Tk_Get3DBorder + 134
	9   libtk8.6.dylib                      0x000000010f01d74f Tk_Alloc3DBorderFromObj + 127
	10  libtk8.6.dylib                      0x000000010f02efad DoObjConfig + 941
	11  libtk8.6.dylib                      0x000000010f02eae5 Tk_InitOptions + 357
	12  libtk8.6.dylib                      0x000000010f02e9c5 Tk_InitOptions + 69
	13  libtk8.6.dylib                      0x000000010f05fb5c CreateFrame + 1548
	14  libtk8.6.dylib                      0x000000010f05fe37 TkListCreateFrame + 151
	15  libtk8.6.dylib                      0x000000010f0577f8 Initialize + 2168
	16  _tkinter.cpython-38-darwin.so       0x000000010ee8968b Tcl_AppInit + 91
	17  _tkinter.cpython-38-darwin.so       0x000000010ee8934e Tkapp_New + 590
	18  _tkinter.cpython-38-darwin.so       0x000000010ee890ee _tkinter_create_impl + 222
	19  _tkinter.cpython-38-darwin.so       0x000000010ee88bd6 _tkinter_create + 182
	20  python                              0x000000010ea31644 cfunction_vectorcall_FASTCALL + 84
	21  python                              0x000000010eb0af20 _PyEval_EvalFrameDefault + 45072
	22  python                              0x000000010eafe12d _PyEval_EvalCodeWithName + 557
	23  python                              0x000000010e9d519a _PyFunction_Vectorcall + 426
	24  python                              0x000000010eb0af20 _PyEval_EvalFrameDefault + 45072
	25  python                              0x000000010e9d50e8 _PyFunction_Vectorcall + 248
	26  python                              0x000000010e9d37dd _PyObject_FastCallDict + 93
	27  python                              0x000000010ea59f52 slot_tp_init + 178
	28  python                              0x000000010ea694c1 type_call + 289
	29  python                              0x000000010e9d3ad7 _PyObject_MakeTpCall + 167
	30  python                              0x000000010eb0b3d1 _PyEval_EvalFrameDefault + 46273
	31  python                              0x000000010eafe12d _PyEval_EvalCodeWithName + 557
	32  python                              0x000000010eaf9029 builtin_exec + 329
	33  python                              0x000000010ea31644 cfunction_vectorcall_FASTCALL + 84
	34  python                              0x000000010eb0b2b0 _PyEval_EvalFrameDefault + 45984
	35  python                              0x000000010eafe12d _PyEval_EvalCodeWithName + 557
	36  python                              0x000000010e9d519a _PyFunction_Vectorcall + 426
	37  python                              0x000000010eb0b2b0 _PyEval_EvalFrameDefault + 45984
	38  python                              0x000000010eafe12d _PyEval_EvalCodeWithName + 557
	39  python                              0x000000010e9d519a _PyFunction_Vectorcall + 426
	40  python                              0x000000010e9d44a9 PyVectorcall_Call + 121
	41  python                              0x000000010eb9ded1 pymain_run_module + 225
	42  python                              0x000000010eb9d8b7 pymain_run_python + 279
	43  python                              0x000000010eb9d745 Py_RunMain + 37
	44  python                              0x000000010eb9ee11 pymain_main + 49
	45  python                              0x000000010e9a7768 main + 56
	46  libdyld.dylib                       0x00007fff6e38ecc9 start + 1
	47  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
zsh: abort      python -m minecraft

**Comment by jason-bowen-zheng** [comment]
`NSException` is what?

Okay, This issue is very difficult to solve because I don't have a Mac.

It seems this exception is from tkinter.
