### ISSUE TITLE
[Suggestions!]

### ISSUE THREAD

**Issue by Bugleman** [Minecraft-in-python/Minecraft#31]
1. English, the english hurts my head in this game.
2. 2. GUI's. The gui's are off centered and sometimes text is randomly floating // when fullscreen
3. Some stuff isnt loading for me.

**Comment by jason-bowen-zheng** [comment]
> 1. English, the english hurts my head in this game.

Yeah, my mother tongue isn't English and I'm learning English now.
> 2. 2. GUI's. The gui's are off centered and sometimes text is randomly floating // when fullscreen

I'm considering rewrite **all code** in the repo so that all issue may be solved.
> 3. Some stuff isnt loading for me.

Can you explain more clearly?

**Comment by Bugleman** [comment]
> Can you explain more clearly?
Yes, some UI/GUI's are not loading or / not functioning/working correctly!
I would love to see a survival mode for this game as-well.
As i see you have been working on in the files

**Comment by jason-bowen-zheng** [comment]
The survival mode? Well, It seems too hard for the structure of the code now.

> GUIs are not working correctly!

I know. It's not a WYSIWYG environment. I have paid great effort on it(it can't work well finally).

> As I see you have been working on in the files.

I **have been**. But thousands lines of code isn't a easy job(briefly, I'm very busy for other things).
