### ISSUE TITLE
i git clone command on doccumentation was wrong

### ISSUE THREAD

**Issue by darkrabel** [Minecraft-in-python/Minecraft#32]
# the site says 
-
git clone htts://github.com/Minecraft-in-python/Minecraft
# there is not htts protocol it will https .

**Comment by jason-bowen-zheng** [comment]
which site?

**Comment by darkrabel** [comment]
> which site?

the readme of the official repo.

**Comment by jason-bowen-zheng** [comment]
I'm still confusing! Let me ask you more clearly: which repo?

Every url seems right.
