### ISSUE TITLE
it stops at the MINECRAFT PYTHON EDITION page(? idk wat happened 

### ISSUE THREAD

**Issue by mateusz-starok** [Minecraft-in-python/Minecraft#34]

**Comment by mateusz-starok** [comment]
but......... how is it supposed to run though

**Comment by jason-bowen-zheng** [comment]
> but......... how is it supposed to run though

You have ran the program in the right way! I'm rewriting the whole repo now.
The start scene shows "Minecraft Python Edition" is the result right now.
