### ISSUE TITLE
it shows this "TSM AdjustCapsLockLEDForKeyTransitionHandling - _ISSetPhysicalKeyboardCapsLockLED Inhibit

### ISSUE THREAD

**Issue by voldeXiago** [Minecraft-in-python/Minecraft#35]

**Comment by aidaner** [comment]
what

**Comment by jason-bowen-zheng** [comment]
@mateusz-starok please use spaces(` `) to split each work. And meaningless issue will be closed.

It seems that this issue isn't belong to this repo.

**Comment by jason-bowen-zheng** [comment]
@mateusz-starok If you want to solve this issue here. Please tell us:

 1. what cause this issue
 2. the output of program
 3. (optional) where go wrong

**Comment by snailshen2014** [comment]
me too,as starting the minescraft,the program hung.

**Comment by jason-bowen-zheng** [comment]
@snailshen2014 which OS do you use? I think the game(and the game before rewrite) isn't support MacOS.

I think you should go to [pyglet/pyglet](https://github.com/pyglet/pyglet) to start an issue.

**Comment by jason-bowen-zheng** [comment]
You should care about the [minecraft/\_\_main_\_\.py](https://github.com/Minecraft-in-python/Minecraft/blob/master/minecraft/__main__.py) file, which starts the game.

**Comment by snailshen2014** [comment]
> 

Yes, i ran this game on the MacOS

**Comment by jason-bowen-zheng** [comment]
@snailshen2014 Did the program or OS log a lot of information?

Maybe you should open an issue [here](https://github.com/pyglet/pyglet/issues/new), this is the problem of game engine.

**Comment by snailshen2014** [comment]
3ks
