### ISSUE TITLE
[feature] crash report

### ISSUE THREAD

**Issue by shenjackyuanjie** [Minecraft-in-python/Minecraft#36]
是不是作为一个正经游戏，是时候加一个crash report系统了呢？（

**Comment by jason-bowen-zheng** [comment]
阁下的建议十分的接地气，实现起来也非常简单（不过我没有用内置的`logging`，但这不成问题）。

阁下是没有找到主要矛盾：没钱啊！绝对不会有公司/组织为我们提供免费服务。如果只是上传崩溃时的日志那根本不够吧，仿照Mojang的做法是不是还得搞一个与我们现在使用的反馈issue十分相似的功能？
> 当然没钱是建立在没有免费服务的前提下。

综上：虽然这个建议很好，但是会花钱，而且花出去的钱再赚回来是不可能的。对于一介穷学生（补充一下：组织内3人都是学生），**我对您的意见持保留态度**。
> 即作为开发者的我不会去实现，但万一有人愿意帮我们那我倒是不反对。

**Comment by shenjackyuanjie** [comment]
> 阁下的建议十分的接地气，实现起来也非常简单（不过我没有用内置的`logging`，但这不成问题）。
> 
> 阁下是没有找到主要矛盾：没钱啊！绝对不会有公司/组织为我们提供免费服务。如果只是上传崩溃时的日志那根本不够吧，仿照Mojang的做法是不是还得搞一个与我们现在使用的反馈issue十分相似的功能？
> 
> > 当然没钱是建立在没有免费服务的前提下。
> 
> 综上：虽然这个建议很好，但是会花钱，而且花出去的钱再赚回来是不可能的。对于一介穷学生（补充一下：组织内3人都是学生），**我对您的意见持保留态度**。
> 
> > 即作为开发者的我不会去实现，但万一有人愿意帮我们那我倒是不反对。

那个（
你可能理解错我的意思了
我表达的是
如果游戏有崩溃，那么输出一个包含  崩溃信息(stack trace)  系统信息  可能的解决方式   崩溃的可能原因
之类的crash report 文件
（可以参考Difficult Rocket  的实现方式   （你可以clone下来之后直接start.cmd运行一下试试））
另外如果你lazy的话（不是） 
我也可以照着DR的实现方式给你实现一遍（

**Comment by shenjackyuanjie** [comment]
另外，crashreport创建出来之后 完全可以让对面直接发你qq文件/截图

**Comment by jason-bowen-zheng** [comment]
我了解了您的想法。不过，我在[__main__.py](https://github.com/Minecraft-in-python/Minecraft/blob/master/minecraft/__main__.py)中实现了崩溃信息（或traceback）的输出及保存到本地文件系统的功能。至于要怎么处理这些日志嘛，那就随便用户喽！

让别人发我QQ（微信/telegram）？说实话，绝大多数运行该游戏的人都是在GitHub上获取的，他们可以通过issues把错误反馈给我。

**Comment by jason-bowen-zheng** [comment]
如果这些都不行，README中有一个"chat on gitter"，点击即可进入一个聊天室，里面也可以反馈意见（似乎不用了）。

**Comment by shenjackyuanjie** [comment]
确实，不过感觉可以写的更好一些（逃，这就去写pr（

**Comment by jason-bowen-zheng** [comment]
感谢阁下的建议，那我就关闭这个issue喽！

**Comment by shenjackyuanjie** [comment]
不愧是你（
