### ISSUE TITLE
[BUG] run.bat脚本异常

### ISSUE THREAD

**Issue by Khaimin6** [Minecraft-in-python/Minecraft#40]
### 操作系统

Windows

### Python解释器

3.9

### 具体问题

install.py 启动脚本指令有错别字
active应该为activate，deactive也是同理。

**Comment by jason-bowen-zheng** [comment]
感谢阁下的提醒，对`install.py`的修改将在近期提交。

**Comment by Khaimin6** [comment]
为什么要创建虚拟环境啊？现在的BAT文件根本没法运行。
https://stackoverflow.com/questions/24678144/conda-environments-and-bat-files

**Comment by jason-bowen-zheng** [comment]
我认为这样做是必要的。

从长远来看（其实现在已需要），这个游戏的依赖项到时候会变得很多，总有一天依赖项会有版本冲突。那么虚拟环境可以解决这个问题。

再者，阁下提到的这个问题貌似已经解决（在我的win7上可正常运行，不存在问题）。

~~如果不想创建虚拟环境，那么可以在代码层面更改python的导入规则（较复杂）。~~

如果阁下有什么更合适的方法，请详细说明。
